# Generated by Django 4.2.6 on 2023-10-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='difficulty',
            field=models.CharField(default='x', max_length=1),
        ),
    ]
