# Generated by Django 4.2.6 on 2023-11-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_song_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artistname',
            field=models.CharField(default='x', max_length=30),
        ),
    ]
