# Generated by Django 4.2.6 on 2023-11-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_song_artistname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='difficulty',
        ),
    ]
