# Generated by Django 4.2.6 on 2023-11-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_song_difficulty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
        migrations.AlterField(
            model_name='song',
            name='artistname',
            field=models.CharField(max_length=30),
        ),
    ]
